# Generated by Django 5.0.6 on 2024-05-18 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('current_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classes.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teachers.teacher')),
            ],
        ),
    ]
